spring:
  application:
    name: userservice
  datasource:
    url: jdbc:mysql://localhost:3306/fitness_user_db
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect